### ISSUE TITLE
Unable to join the game due to version detection ? 

### ISSUE THREAD

**Issue by Klosw** [TheSlayerMC/JITL#11]
JITL 1.20.1  

```
[10五月2024 14:19:18.990] [Server thread/ERROR] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: Couldn't place player in world
java.lang.RuntimeException: java.net.UnknownHostException: raw.githubusercontent.com
	at net.jitl.client.ClientLoginChecker.onPlayerLogin(ClientLoginChecker.java:49) ~[%5B光明之旅·神之本质%5D%20JITL%20-%201.20.1%20-%202.1.4.jar%23190!/:?]
	at net.jitl.client.__ClientLoginChecker_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[%5B光明之旅·神之本质%5D%20JITL%20-%201.20.1%20-%202.1.4.jar%23190!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23137!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23137!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23137!/:?]
	at net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedIn(ForgeEventFactory.java:875) ~[forge-1.20.1-47.2.30-universal.jar%23217!/:?]
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:261) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:139) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:126) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:70) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23212!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by AllShamNoWow101** [comment]
For now you can disable version checker with a config in the config file

**Comment by Klosw** [comment]
嗯 通过配置文件确实可以关闭检查版本 ,从而跳过版本检查进入游戏
