### ISSUE TITLE
Cannot run JITL on server in 1.19.4

### ISSUE THREAD

**Issue by daftonbb** [TheSlayerMC/JITL#16]
I have been trying to run JITL on my server yet keep getting this error:
Failure message: Journey Into the Light (jitl) has failed to load correctly
		java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/DimensionSpecialEffects for invalid dist DEDICATED_SERVER
	Mod Version: 1.19.4-2.0.0.8
	Mod Issue URL: https://github.com/TheSlayerMC/JITL/issues
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/DimensionSpecialEffects for invalid dist DEDICATED_SERVER

I am unsure of what to do to fix it. The entire crash reports reads as this:
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:58) ~[forge-1.19.4-45.3.0-universal.jar%23170!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.19.4-45.3.0-universal.jar%23170!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:125) ~[server-1.19.4-20230314.122934-srg.jar%23165!/:?] {re:classloading}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.4-45.3.0.jar%2367!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Suspected Mods: NONE
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19.4-45.3.0.jar%2367!/:1.0] {}
-- MOD jitl --
Details:
	Mod File: /C:/Users/dawni/OneDrive/Desktop/hardcore/mods/Journey-Into-The-Light-1.19.4-2.0.0.8.jar
	Failure message: Journey Into the Light (jitl) has failed to load correctly
		java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/DimensionSpecialEffects for invalid dist DEDICATED_SERVER
	Mod Version: 1.19.4-2.0.0.8
	Mod Issue URL: https://github.com/TheSlayerMC/JITL/issues
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/DimensionSpecialEffects for invalid dist DEDICATED_SERVER
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19.4-45.3.0.jar%2367!/:1.0] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar%2354!/:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.6.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.6.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.6.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.6.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.6.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at net.jitl.core.init.JITL.<init>(JITL.java:68) ~[Journey-Into-The-Light-1.19.4-2.0.0.8.jar%23151!/:1.19.4-2.0.0.8] {re:classloading}
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.19.4-45.3.0.jar%23167!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:122) ~[fmlcore-1.19.4-45.3.0.jar%23166!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1489) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2071) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2033) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 22.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 227363512 bytes (216 MiB) / 553648128 bytes (528 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2484
	Graphics card #0 versionInfo: DriverVersion=31.0.15.4633
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 20382.65
	Virtual memory used (MB): 13445.22
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 117.94
	JVM Flags: 1 total; -Xmx6G
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.4-45.3.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.4-45.3.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.4-45.3.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.4-45.3.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.4-45.3.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		server-1.19.4-20230314.122934-srg.jar             |Minecraft                     |minecraft                     |1.19.4              |COMMON_SET|Manifest: NOSIGNATURE
		ExtraArmor-1.19.4-1.17.3.jar                      |Extra Armor                   |extraarmor                    |1.17.2              |COMMON_SET|Manifest: NOSIGNATURE
		elytraslot-forge-6.2.1+1.19.4.jar                 |Elytra Slot                   |elytraslot                    |6.2.1+1.19.4        |COMMON_SET|Manifest: NOSIGNATURE
		zaynens_ender_dragon_dragon_egg_item_drop_mod_1.19|EnderDragonDragonEggItemDrop  |enderdragondragoneggitemdrop  |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterDungeons-1.19.4-Forge-3.4.0.jar        |YUNG's Better Dungeons        |betterdungeons                |1.19.4-Forge-3.4.0  |COMMON_SET|Manifest: NOSIGNATURE
		alchemylib-1.19.4-1.0.22.jar                      |AlchemyLib                    |alchemylib                    |1.19.4-1.0.22       |COMMON_SET|Manifest: NOSIGNATURE
		Journey-Into-The-Light-1.19.4-2.0.0.8.jar         |Journey Into the Light        |jitl                          |1.19.4-2.0.0.8      |ERROR     |Manifest: NOSIGNATURE
		Cucumber-1.19.4-6.2.4.jar                         |Cucumber Library              |cucumber                      |6.2.4               |COMMON_SET|Manifest: NOSIGNATURE
		ImmersiveEngineering-1.19.4-9.4.1-168.jar         |Immersive Engineering         |immersiveengineering          |1.19.4-9.4.1-168    |COMMON_SET|Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		geckolib-forge-1.19.4-4.2.jar                     |GeckoLib 4                    |geckolib                      |4.2                 |COMMON_SET|Manifest: NOSIGNATURE
		aether-1.19.4-1.4.2-forge.jar                     |The Aether                    |aether                        |1.19.4-1.4.2-forge  |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.19.4-forge-13.1.0.18.jar                    |Just Enough Items             |jei                           |13.1.0.18           |COMMON_SET|Manifest: NOSIGNATURE
		supermartijn642corelib-1.1.17-forge-mc1.19.4.jar  |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.17              |COMMON_SET|Manifest: NOSIGNATURE
		caelus-forge-1.19.4-3.0.0.10.jar                  |Caelus API                    |caelus                        |1.19.4-3.0.0.10     |COMMON_SET|Manifest: NOSIGNATURE
		InsaneLib-1.9.2-mc1.19.4.jar                      |InsaneLib                     |insanelib                     |1.9.2               |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-1.19.4-5.1.5.4.jar                   |Curios API                    |curios                        |1.19.4-5.1.5.4      |COMMON_SET|Manifest: NOSIGNATURE
		Patchouli-1.19.4-79.1-FORGE.jar                   |Patchouli                     |patchouli                     |1.19.4-79.1-FORGE   |COMMON_SET|Manifest: NOSIGNATURE
		enlightend-5.0.2-1.19.4.jar                       |Enlightend                    |enlightened_end               |5.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		gravestone-1.19.4-1.0.3.jar                       |Gravestone Mod                |gravestone                    |1.19.4-1.0.3        |COMMON_SET|Manifest: NOSIGNATURE
		Croptopia-1.19.4-FORGE-2.2.2.jar                  |Croptopia                     |croptopia                     |2.2.2               |COMMON_SET|Manifest: NOSIGNATURE
		chemlib-1.19.4-2.0.17.jar                         |ChemLib                       |chemlib                       |1.19.4-2.0.17       |COMMON_SET|Manifest: NOSIGNATURE
		citadel-2.3.4-1.19.4.jar                          |Citadel                       |citadel                       |2.3.4               |COMMON_SET|Manifest: NOSIGNATURE
		alexsmobs-1.22.3.jar                              |Alex's Mobs                   |alexsmobs                     |1.22.3              |COMMON_SET|Manifest: NOSIGNATURE
		L_Enders_Cataclysm-0.84-1.19.4-Hurt-Fix.jar       |Cataclysm Mod                 |cataclysm                     |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
		TravelersBackpack-1.19.4-8.4.20.jar               |Traveler's Backpack           |travelersbackpack             |8.4.20              |COMMON_SET|Manifest: NOSIGNATURE
		Nullscape_1.19.4_v1.2.2 (1).jar                   |Nullscape                     |nullscape                     |1.2.2               |COMMON_SET|Manifest: NOSIGNATURE
		YungsApi-1.19.4-Forge-3.10.1.jar                  |YUNG's API                    |yungsapi                      |1.19.4-Forge-3.10.1 |COMMON_SET|Manifest: NOSIGNATURE
		mixinextras-forge-0.2.0-beta.9.jar                |MixinExtras                   |mixinextras                   |0.2.0-beta.9        |COMMON_SET|Manifest: NOSIGNATURE
		cumulus_menus-1.19.4-1.0.0-forge.jar              |Cumulus                       |cumulus_menus                 |1.19.4-1.0.0-forge  |COMMON_SET|Manifest: NOSIGNATURE
		ProgressiveBosses-3.8.4-mc1.19.4.jar              |Progressive Bosses            |progressivebosses             |3.8.4               |COMMON_SET|Manifest: NOSIGNATURE
		connectedglass-1.1.6-forge-mc1.19.3.jar           |Connected Glass               |connectedglass                |1.1.6               |COMMON_SET|Manifest: NOSIGNATURE
		nitrogen_internals-1.19.4-1.0.5-forge.jar         |Nitrogen                      |nitrogen_internals            |1.19.4-1.0.5-forge  |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterNetherFortresses-1.19.4-Forge-1.2.0.jar|YUNG's Better Nether Fortresse|betterfortresses              |1.19.4-Forge-1.2.0  |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19.4-45.3.0-universal.jar                 |Forge                         |forge                         |45.3.0              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		MysticalAgriculture-1.19.4-6.2.4.jar              |Mystical Agriculture          |mysticalagriculture           |6.2.4               |COMMON_SET|Manifest: NOSIGNATURE
		DungeonsArise-1.19.4-2.1.54-beta.jar              |When Dungeons Arise           |dungeons_arise                |2.1.54-1.19.4       |COMMON_SET|Manifest: NOSIGNATURE
		alchemistry-1.19.4-2.3.0.jar                      |Alchemistry                   |alchemistry                   |1.19.4-2.3.0        |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: c14d495d-8b41-441d-852f-d351b37dd028
	FML: 45.3
	Forge: net.minecraftforge:45.3.0

**Comment by AllShamNoWow101** [comment]
1.20.1+ is when server compatibility came into it, anything prior is not compatible and a dead version
